# Generated by Django 4.0 on 2022-12-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.BigIntegerField()),
                ('nome_completo', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
    ]
