# Generated by Django 4.0 on 2022-12-31 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppClientes', '0002_clientes_table_delete_clientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes_table',
            options={'managed': False},
        ),
    ]
