# Generated by Django 4.0 on 2022-12-31 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppClientes', '0004_alter_clientes_table_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes_table',
            options={'managed': True},
        ),
    ]
