# Generated by Django 4.0 on 2023-01-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClientes', '0007_clientes_delete_clientes_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_os',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_os', models.CharField(db_column='nome_tipo_os', max_length=100)),
            ],
            options={
                'db_table': 'tipos_os',
                'managed': False,
            },
        ),
    ]
