# Generated by Django 4.0 on 2023-01-04 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppClientes', '0008_tipo_os'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tipo_os',
        ),
    ]
