# Generated by Django 4.0 on 2023-01-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ordem_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pecas', models.IntegerField(db_column='numero_pecas')),
                ('status', models.CharField(db_column='status', max_length=20)),
                ('previsao_entrega', models.DateField(db_column='previsao_entrega')),
                ('dt_entrada', models.DateField(db_column='dt_entrada')),
                ('dt_concluida', models.DateField(db_column='dt_concluida')),
                ('dt_entrega', models.DateField(db_column='dt_entrega')),
                ('preco_total', models.DecimalField(db_column='preco_total', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ordem_servico',
                'managed': False,
            },
        ),
    ]
